/***************************************************************
 * Publication version
 * Persistent bare-soil exposure indicator from Sentinel-2
 * Minsk Region, Belarus, 2020–2025
 *
 * Manuscript:
 * Persistent Bare-Soil Exposure as a Sentinel-2 Ecological Indicator
 * of Recurrent Land-Surface Pressure in Temperate Agricultural Landscapes
 *
 * Notes:
 * 1. Replace placeholder asset IDs before running.
 * 2. Script 01 generates annual bare_frac products.
 * 3. Downstream modules use the annual products generated by Script 01.
 * 4. Some institutional datasets used in the manuscript are not redistributed.
 ***************************************************************/


// =============================================================
// 0. USER SETTINGS
// =============================================================

// Replace with your own public or private GEE asset paths.
var AOI_ASSET = 'users/your_account/study_area_boundary';
var DISTRICTS_ASSET = 'users/your_account/district_boundaries';

// Root folder where annual products generated by this script are stored.
var OUTPUT_ASSET_ROOT = 'users/your_account';

// Study years.
var YEARS = [2020, 2021, 2022, 2023, 2024, 2025];

// Sentinel-2 and indicator parameters.
var TH_NDVI = 0.20;
var TH_BSI  = 0.18;
var TH_NDBI = 0.20;

var MIN_OBS_YEAR = 10;
var MAX_SCENE_CLOUD = 80;

var CRS = 'EPSG:32635';
var SCALE_10 = 10;
var SCALE_30 = 30;

// Set true/false depending on which modules you want to run.
var RUN_ANNUAL_EXPORTS = false;
var RUN_METADATA_TABLES = true;
var RUN_PERSISTENCE_SENSITIVITY = true;
var RUN_ANNUAL_AREA_SUMMARY = true;
var RUN_RECURRENCE_MAP = true;
var RUN_CANDIDATE_REFERENCE_POINTS = false;


// =============================================================
// 1. LOAD CORE INPUTS
// =============================================================

var AOI = ee.FeatureCollection(AOI_ASSET).geometry();
var districts = ee.FeatureCollection(DISTRICTS_ASSET);

var worldCover = ee.Image('ESA/WorldCover/v200/2021')
  .select('Map')
  .clip(AOI);

// ESA WorldCover class 50 = built-up.
var NON_BUILT_MASK = worldCover.neq(50).rename('non_built');


// =============================================================
// 2. SENTINEL-2 PREPROCESSING
// =============================================================

function prepImage(img) {
  var scl = img.select('SCL');

  // Valid SCL classes used in the manuscript workflow:
  // 4 = vegetation, 5 = non-vegetated, 7 = unclassified.
  var valid = scl.eq(4).or(scl.eq(5)).or(scl.eq(7));

  var sr = img.updateMask(valid)
    .select(['B2', 'B3', 'B4', 'B8', 'B11', 'B12'])
    .multiply(0.0001);

  var ndvi = sr.normalizedDifference(['B8', 'B4']).rename('NDVI');

  var bsi = sr.expression(
    '((SWIR1 + RED) - (NIR + BLUE)) / ((SWIR1 + RED) + (NIR + BLUE))',
    {
      SWIR1: sr.select('B11'),
      RED: sr.select('B4'),
      NIR: sr.select('B8'),
      BLUE: sr.select('B2')
    }
  ).rename('BSI');

  var ndbi = sr.normalizedDifference(['B11', 'B8']).rename('NDBI');

  var ndmi = sr.normalizedDifference(['B8', 'B11']).rename('NDMI');

  var bare = bsi.gt(TH_BSI)
    .and(ndvi.lt(TH_NDVI))
    .and(ndbi.lt(TH_NDBI))
    .and(NON_BUILT_MASK.eq(1))
    .rename('bare')
    .uint8();

  var obs = ee.Image.constant(1)
    .updateMask(valid)
    .rename('obs')
    .uint8();

  return sr.addBands([ndvi, bsi, ndbi, ndmi, bare, obs])
    .copyProperties(img, ['system:time_start']);
}


function getS2Collection(start, end) {
  return ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterDate(start, end)
    .filterBounds(AOI)
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', MAX_SCENE_CLOUD))
    .map(prepImage);
}


// =============================================================
// 3. MODULE 01: ANNUAL bare_frac PRODUCTS
// =============================================================

function makeAnnualBareFrac(year) {
  var start = ee.Date.fromYMD(year, 1, 1);
  var end = start.advance(1, 'year');

  var col = getS2Collection(start, end);

  var bareSum = col.select('bare').sum().rename('bare_sum').toFloat();
  var obsCount = col.select('obs').sum().rename('obs_count').toFloat();

  var bareFrac = bareSum
    .divide(obsCount.max(1))
    .updateMask(obsCount.gte(MIN_OBS_YEAR))
    .rename('bare_frac')
    .toFloat();

  return ee.Image.cat([bareSum, obsCount, bareFrac])
    .clip(AOI)
    .toFloat()
    .set('year', year);
}


function annualAssetId(year) {
  return OUTPUT_ASSET_ROOT + '/Minsk_Annual_BareSoil_' + year;
}


if (RUN_ANNUAL_EXPORTS) {
  YEARS.forEach(function(year) {
    var annual = makeAnnualBareFrac(year);

    Export.image.toAsset({
      image: annual,
      description: 'Minsk_Annual_BareSoil_' + year,
      assetId: annualAssetId(year),
      region: AOI,
      crs: CRS,
      scale: SCALE_10,
      maxPixels: 1e13
    });

    Export.image.toDrive({
      image: annual,
      description: 'Minsk_Annual_BareSoil_' + year,
      folder: 'BareSoil_exports',
      fileNamePrefix: 'Minsk_Annual_BareSoil_' + year,
      region: AOI,
      crs: CRS,
      scale: SCALE_10,
      maxPixels: 1e13,
      fileFormat: 'GeoTIFF'
    });
  });
}


// =============================================================
// 4. HELPER: LOAD ANNUAL PRODUCTS GENERATED BY MODULE 01
// =============================================================

function loadAnnualImage(year) {
  return ee.Image(annualAssetId(year)).clip(AOI).toFloat();
}


function loadAnnualCollection() {
  return ee.ImageCollection.fromImages(
    YEARS.map(function(year) {
      return loadAnnualImage(year).set('year', year);
    })
  );
}


// =============================================================
// 5. MODULE 02: SCENE COUNT AND OBSERVATION METADATA
// =============================================================

function rawCollection(start, end) {
  return ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
    .filterDate(start, end)
    .filterBounds(AOI)
    .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', MAX_SCENE_CLOUD));
}


function sceneCountFeature(year) {
  var yStart = ee.Date.fromYMD(year, 1, 1);
  var q1Start = ee.Date.fromYMD(year, 1, 1);
  var q2Start = ee.Date.fromYMD(year, 4, 1);
  var q3Start = ee.Date.fromYMD(year, 7, 1);
  var q4Start = ee.Date.fromYMD(year, 10, 1);
  var yEnd = yStart.advance(1, 'year');

  return ee.Feature(null, {
    year: year,
    Q1_scenes: rawCollection(q1Start, q2Start).size(),
    Q2_scenes: rawCollection(q2Start, q3Start).size(),
    Q3_scenes: rawCollection(q3Start, q4Start).size(),
    Q4_scenes: rawCollection(q4Start, yEnd).size(),
    annual_scenes: rawCollection(yStart, yEnd).size()
  });
}


function obsSummaryFeature(year) {
  var img = loadAnnualImage(year);

  var stats = img.select('obs_count').reduceRegion({
    reducer: ee.Reducer.mean()
      .combine(ee.Reducer.min(), '', true)
      .combine(ee.Reducer.max(), '', true)
      .combine(ee.Reducer.stdDev(), '', true),
    geometry: AOI,
    scale: SCALE_30,
    maxPixels: 1e13,
    bestEffort: true
  });

  return ee.Feature(null, {
    year: year,
    obs_mean: stats.get('obs_count_mean'),
    obs_min: stats.get('obs_count_min'),
    obs_max: stats.get('obs_count_max'),
    obs_std: stats.get('obs_count_stdDev')
  });
}


if (RUN_METADATA_TABLES) {
  var sceneTable = ee.FeatureCollection(YEARS.map(sceneCountFeature));
  var obsSummaryTable = ee.FeatureCollection(YEARS.map(obsSummaryFeature));

  print('Scene count table:', sceneTable);
  print('Observation summary table:', obsSummaryTable);

  Export.table.toDrive({
    collection: sceneTable,
    description: 'Minsk_Scene_Count_Metadata_2020_2025',
    fileFormat: 'CSV'
  });

  Export.table.toDrive({
    collection: obsSummaryTable,
    description: 'Minsk_ObsCount_Summary_2020_2025',
    fileFormat: 'CSV'
  });
}


// =============================================================
// 6. MODULE 03: PERSISTENCE THRESHOLD SENSITIVITY
// =============================================================

function computePersistentYears(threshold) {
  var annualCol = loadAnnualCollection();

  var persistentCol = annualCol.map(function(img) {
    return img.select('bare_frac').gte(threshold)
      .and(img.select('obs_count').gte(MIN_OBS_YEAR))
      .rename('persistent')
      .toFloat();
  });

  return persistentCol.sum().toFloat();
}


if (RUN_PERSISTENCE_SENSITIVITY) {
  var p03 = computePersistentYears(0.30).rename('persistent_years_03');
  var p05 = computePersistentYears(0.50).rename('persistent_years_05');
  var p07 = computePersistentYears(0.70).rename('persistent_years_07');

  var sensitivityStack = ee.Image.cat([p03, p05, p07]).toFloat();

  Map.centerObject(AOI, 7);
  Map.addLayer(p05, {min: 0, max: 6, palette: ['ffffff', 'fee5d9', 'fcae91', 'fb6a4a', 'de2d26', 'a50f15']}, 'Persistent years TH0.5');

  Export.image.toAsset({
    image: sensitivityStack,
    description: 'Minsk_Persistence_Sensitivity',
    assetId: OUTPUT_ASSET_ROOT + '/Minsk_Persistence_Sensitivity',
    region: AOI,
    crs: CRS,
    scale: SCALE_30,
    maxPixels: 1e13
  });

  Export.image.toDrive({
    image: sensitivityStack,
    description: 'Minsk_Persistence_Sensitivity',
    folder: 'BareSoil_exports',
    fileNamePrefix: 'Minsk_Persistence_Sensitivity',
    region: AOI,
    crs: CRS,
    scale: SCALE_30,
    maxPixels: 1e13,
    fileFormat: 'GeoTIFF'
  });
}


// =============================================================
// 7. MODULE 04: ANNUAL PERSISTENT AREA SUMMARY
// =============================================================

function calcPersistentArea(img, threshold) {
  var mask = img.select('bare_frac').gte(threshold)
    .and(img.select('obs_count').gte(MIN_OBS_YEAR));

  var areaImg = mask.multiply(ee.Image.pixelArea().divide(1e6)).rename('area_km2');

  return areaImg.reduceRegion({
    reducer: ee.Reducer.sum(),
    geometry: AOI,
    scale: SCALE_30,
    maxPixels: 1e13,
    bestEffort: true
  }).getNumber('area_km2');
}


if (RUN_ANNUAL_AREA_SUMMARY) {
  var annualAreaTable = ee.FeatureCollection(
    YEARS.map(function(year) {
      var img = loadAnnualImage(year);

      return ee.Feature(null, {
        year: year,
        persistent_area_th05_km2: calcPersistentArea(img, 0.50),
        persistent_area_th07_km2: calcPersistentArea(img, 0.70)
      });
    })
  );

  print('Annual persistent area table:', annualAreaTable);

  Export.table.toDrive({
    collection: annualAreaTable,
    description: 'Minsk_Annual_PersistentArea_2020_2025',
    fileFormat: 'CSV'
  });
}


// =============================================================
// 8. MODULE 05: SIX-YEAR HOTSPOT RECURRENCE MAP
// =============================================================

if (RUN_RECURRENCE_MAP) {
  var recurrence = loadAnnualCollection().map(function(img) {
    return img.select('bare_frac').gte(0.50)
      .and(img.select('obs_count').gte(MIN_OBS_YEAR))
      .rename('hotspot')
      .toByte();
  }).sum()
    .rename('hotspot_recurrence')
    .toByte()
    .clip(AOI);

  Map.centerObject(AOI, 7);
  Map.addLayer(
    recurrence,
    {
      min: 0,
      max: 6,
      palette: ['ffffff', 'fff7bc', 'fee391', 'fec44f', 'fe9929', 'ec7014', 'cc4c02']
    },
    'Hotspot recurrence TH0.5, 2020–2025'
  );

  var areaImg = ee.Image.pixelArea().divide(1e6).rename('area_km2');
  var recurrenceClasses = ee.List.sequence(0, 6);

  var recurrenceTable = ee.FeatureCollection(
    recurrenceClasses.map(function(c) {
      c = ee.Number(c);

      var area = recurrence.eq(c)
        .multiply(areaImg)
        .rename('area_km2')
        .reduceRegion({
          reducer: ee.Reducer.sum(),
          geometry: AOI,
          scale: SCALE_10,
          maxPixels: 1e13,
          bestEffort: true
        }).getNumber('area_km2');

      return ee.Feature(null, {
        recurrence_years: c,
        area_km2: area
      });
    })
  );

  print('Recurrence table:', recurrenceTable);

  Export.image.toDrive({
    image: recurrence,
    description: 'Minsk_Hotspot_Recurrence_TH05_2020_2025',
    folder: 'BareSoil_exports',
    fileNamePrefix: 'Minsk_Hotspot_Recurrence_TH05_2020_2025',
    region: AOI,
    crs: CRS,
    scale: SCALE_10,
    maxPixels: 1e13,
    fileFormat: 'GeoTIFF'
  });

  Export.table.toDrive({
    collection: recurrenceTable,
    description: 'Minsk_Hotspot_Recurrence_Table_TH05_2020_2025',
    fileFormat: 'CSV'
  });
}


// =============================================================
// 9. MODULE 06: CANDIDATE REFERENCE POINTS FOR MANUAL INTERPRETATION
// =============================================================

function quarterDates(year, quarter) {
  var start;
  var end;

  if (quarter === 'Q2') {
    start = ee.Date.fromYMD(year, 4, 1);
    end = ee.Date.fromYMD(year, 7, 1);
  }

  if (quarter === 'Q3') {
    start = ee.Date.fromYMD(year, 7, 1);
    end = ee.Date.fromYMD(year, 10, 1);
  }

  if (quarter === 'Q4') {
    start = ee.Date.fromYMD(year, 10, 1);
    end = ee.Date.fromYMD(year + 1, 1, 1);
  }

  return {start: start, end: end};
}


function makeQuarterComposite(year, quarter) {
  var d = quarterDates(year, quarter);
  return getS2Collection(d.start, d.end).median().clip(AOI);
}


function makeCandidatePoints(year, quarter) {
  var img = makeQuarterComposite(year, quarter);

  var ruleBare = img.select('BSI').gt(TH_BSI)
    .and(img.select('NDVI').lt(TH_NDVI))
    .and(img.select('NDBI').lt(TH_NDBI))
    .and(NON_BUILT_MASK.eq(1))
    .rename('candidate_class')
    .toByte();

  var points = ruleBare.unmask(0).stratifiedSample({
    numPoints: 350,
    classBand: 'candidate_class',
    region: AOI,
    scale: SCALE_10,
    seed: 42,
    geometries: true
  });

  return points.map(function(f) {
    return f.set({
      year: year,
      quarter: quarter,
      ref: null
    });
  });
}


if (RUN_CANDIDATE_REFERENCE_POINTS) {
  var candidates = makeCandidatePoints(2024, 'Q2')
    .merge(makeCandidatePoints(2024, 'Q3'))
    .merge(makeCandidatePoints(2024, 'Q4'));

  print('Candidate reference points:', candidates);
  print('Candidate class distribution:', candidates.aggregate_histogram('candidate_class'));
  print('Quarter distribution:', candidates.aggregate_histogram('quarter'));

  Export.table.toDrive({
    collection: candidates,
    description: 'Minsk_candidate_reference_points_Q2_Q3_Q4_2024',
    fileFormat: 'SHP'
  });
}
